/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

println(projectDir)

sourceSets {
    main {
        java.srcDir("src")
    }
}

plugins {
    kotlin("jvm") version "1.3.50"
    application
    id 'org.openjfx.javafxplugin' version '0.0.8'
}

application {
    mainClassName = "MainKt"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
}